package com.upsaclay.authentication.domain.entity

enum class AuthenticationScreenState {
    DEFAULT,
    LOADING,
    EMAIL_VERIFIED,
    EMAIL_NOT_VERIFIED,
    INVALID_CREDENTIALS_ERROR,
    EMPTY_FIELDS_ERROR,
    EMAIL_FORMAT_ERROR,
    UNKNOWN_ERROR,
    INTERNAL_SERVER_ERROR,
    NETWORK_ERROR,
    TOO_MANY_REQUESTS_ERROR,
    AUTH_USER_NOT_FOUND
}