package com.upsaclay.authentication.domain.entity

enum class AuthenticationScreenState {
    DEFAULT,
    LOADING,
    EMAIL_VERIFIED,
    EMAIL_NOT_VERIFIED,
    AUTHENTICATION_ERROR,
    EMPTY_FIELDS_ERROR,
    EMAIL_FORMAT_ERROR,
    UNKNOWN_ERROR,
    SERVER_COMMUNICATION_ERROR,
    TOO_MANY_REQUESTS_ERROR,
    SERVER_COMMUNICATION,
    AUTHENTICATED_USER_NOT_FOUND
}