package com.upsaclay.authentication.domain.entity

enum class RegistrationScreenState {
    LOADING,
    REGISTERED,
    NOT_REGISTERED,
    UNRECOGNIZED_ACCOUNT,
    USER_ALREADY_EXISTS,
    EMPTY_FIELDS_ERROR,
    EMAIL_FORMAT_ERROR,
    PASSWORD_LENGTH_ERROR,
    USER_CREATION_ERROR,
    SERVER_COMMUNICATION_ERROR,
    NETWORK_ERROR,
    UNKNOWN_ERROR
}